[project]
name = "fducoursedata"
version = "0.1.0"
description = "Fudan University Course Data Crawler"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.3",
    "tqdm>=4.67.1",
]
